name: UnitedCombat
version: '${project.version}'
main: org.unitedlands.combat.UnitedCombat
api-version: 1.21
authors: [Maroon28]
contributors: [Litning11, Theriel_]
depend: [ Towny ]
softdepend: [ PlaceholderAPI, GSit, AngelChest, AxGraves ]
commands:
  unitedcombat:
    description: Reloads the plugin config.
    usage: /unitedcombat reload
    permission: united.combat.admin
  combatadmin:
    description: Admin commands for UnitedCombat
    aliases: [ca]
    permission: united.combat.admin
  pvp:
     description: Main PVP command. Used to enable and disable pvp status. 